git-fixup

Fixes #9. If the configured upstream is not yielding a non empty
revision range ignore it and consider the full history.

fallback to all commits when rev range is empty

---

Makefile

Adding the `-d` flag to `install` also renders the `mkdir` command redundant in the `install-zsh` target, so I removed that line as well.

When installing, create any missing parent dirs.

---

git-fixup

This partly fixes #19 but introduces some weird output instead. But it
should be slightly better as at least the full error message is visible.

redirect error message to stderr

---

README.md
git-fixup

$ git-fixup -s 492aa0b
[master 2f9b858] squash! 492aa0b10fbf5365c4ab447359223db950f22ad0
The flag must be provided before the git rev.

add support for squashing with the `-s` or `--squash` params

---

completion.zsh

Rewrite to use the `_arguments` helper and a function providing the
fixup bases which also was improved to not call git-fixup twice.
If git-fixup does not yield any commits to use the output to stderr will
be displayed using `_message`

update zsh completion script

---

git-fixup

When generating candidates based on most recent commit to each change
file it can easily happen that the last commit is a fixup created
moments ago. This is not very useful as doing a 2nd fixup of the same
original commit will have the same effect and it's more likely to be
shadowing a commit you actually want to fix.
Add a inverted grep for commit messages starting the line with fixup or
squash when calling rev-list
@fixe @joeshaw  does this look reasonble to you guys?

Exclude other fixups from recent commits

---

git-fixup

The triple dot notation in rev ranges is different to git diff and
rev-list (and blame). In the case of log it would cause commits on
@{upstream} not in the merge base to be included which is causing blame
to exit with a fatal error.

Don't use symmetrical rev range

---

Makefile

Hi,
I would like to package git-fixup for the gentoo distribution since I found it useful and would like to share it with my fellow workers (we are a few to be on gentoo).
The problem is, I discovered that the Makefile of your project doesn't use the `$DESTDIR` variable to allow installation to another place, which is almost mandatory on gentoo.
I hope it won't bother you to add them!
Cheers

Use DESTDIR in Makefile

---

completion.zsh

In Zsh 5.3, the construct `foo=bar | stuff` will no longer leave foo set (which
was accidental), so separating stdout and stderr this way no longer works.
However, it’s not strictly necessary to do so, since the exit status will also
signal failure conditions.
Fixes #35

Fix completion for Zsh 5.3

---

git-fixup

Use read instead of readarray because the latter is only bash >= 4 which isn't available on mac os.

replace readarray

---

README.md
completion.fish
completion.zsh

- Updated the shell completions with `--no-verify`. I did test fish but not zsh.
- Updated the README

No-verify: doc and completion

---

README.md
git-fixup

Hi there!
This is particularly useful for when the local development branch has diverged from its remote counterpart due to a previous rebase. This was the main motivation for me to implement such a feature.
Best regards,  
Gustavo Sousa

Add --base option

---

git-fixup

On d3a301b27b347bb9cde4195ae8d64754262cd7c6 there was a code move that accidentally removed the `target=$1` functionality, forcing the tool to always use the menu instead of using the provided ref
Let me know if I'm missing something (the original commit had a shift, for example), but I think this should be ready to go.

Recover lost `git fixup <ref>` functionality

---

README.md
completion.fish
completion.zsh
git-fixup

Taking the [idea](https://github.com/tummychow/git-absorb) from `git absorb` (a similar tool), I added a simple command line option to call `git rebase` after a commit was made with `git fixup`, instead of having to manually call `git rebase -i ...`
This can be configured as a default with the `fixup.rebase` git config option. This PR also adds the `--no-rebase` option, to bypass any default set.
(As a fun side note, if one would like to [not even have the interactive rebase editor appear](https://stackoverflow.com/a/37224000), you can make `GIT_SECUENCE_EDITOR` point to `touch` and have `git fixup <ref>` be entirely input-less: `GIT_SEQUENCE_EDITOR=touch git fixup <ref>`. Of course this could be made as a feature for `git-fixup`, but I think it shouldn't be one, due to the hacky nature …

Add `--rebase` option that calls rebase after commit

---

completion.fish
completion.zsh
git-fixup

`git commit` supports `-n` as short option for `--no-verify`. We here
now mirror that behavior.

Add short option -n for --no-verify

---

completion.fish

Fish 3.5 did speed up loading custom fish completions. But also changed its behaviour in https://github.com/fish-shell/fish-shell/commit/ff72e3f1543618095ffa03799a93b04f9f868a60. It is now necessary to define at least one custom completion for 'git-fixup'. That pointed to an easier way: Write completions for 'git-fixup' and fish will forward them from 'git fixup' https://github.com/fish-shell/fish-shell/commit/09161761c14f23dec8e8f681ff80140d828080b0

Remove filenames in tab-completion in fish >= 3.5

---

README.md
completion.zsh
git-fixup

Recent git releases accept a `--fixup=amend:<rev>` syntax that allows direct edition of the target commit's message, which can be seen as an improved version of the `--squash` option. Expose that functionality to users via a new option `--amend` (or `-a`).

Add --amend option

---

completion.fish
completion.zsh
git-fixup

This new option allows to display all the commits in the range base..HEAD.
This option does not use all the smart closest commit search in the range. But it allows to use the interactive selection. It is usefull when the user does a modification unrelated to the target commit, and knows which commit it is. In that, it may do:
* git commit -m "fixfix"
* git rebase -i base
This new option saves one command, and is shorted to:
* git fixup -a -b base

Add --all option

---

git-fixup

This is important to not call git rebase with a dirty repository state when the --rebase option is used.
Fixes #68

Fail script if git-commit fails

---

Makefile

A few things I noticed when packaging git-fixup for Gentoo.

Install zsh completion with mode 644, add `install-fish` target

---

README.md
git-fixup

Proposed implementation of #79.
@keis let me know what you think :slightly_smiling_face:

Add sort by time
